### ISSUE TITLE
MattGoodman - Changing presets via keyboard arrow keys.

### ISSUE THREAD

**Issue by musicbynumbers** [cycfi/ascend#10]
Would be great to allow the up and down arrows on the keyboard to cycle presets (unless I missed the shortcut?) This would make it easy to cycle through presets without having to grab the mouse (whilst still holding the guitar).

Doesn't have to be the up and down arrows if there's a better keyboard shortcut for it though. Anything would be great :)

**Comment by djowel** [comment]
Take note that, by design, you should be able to link a MIDI controller to Ascend-VPU's program change param. For example, you can use foot controllers to switch presets, or the Cycfi CV-switch (which generates program change).

(Alas, right now, it seems the program change automation is not currently synced to all channels -- need to fix this)

**Comment by djowel** [comment]
Done.
